---
- hosts: all
  tasks:
    - name: Get Windows version
      win_shell: "systeminfo /fo csv | ConvertFrom-Csv | select OS*, System*, Hotfix* | Format-List"
      register: windows_version

    - name: Print Windows host information
      debug:
        msg: "{{ windows_version }}"
