---
- name: Installing Apache 
  hosts: all

  tasks:
  - name: Download apache(httpd) msi
    win_get_url:
      url: https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi
      dest: C:\Temp\httpd-2.2.25-win32-x86-no_ssl.msi

  - name: Install msi
    win_package:
      path: C:\Temp\httpd-2.2.25-win32-x86-no_ssl.msi
      state: present

  - name: Remove msi
    win_file:
      path: C:\Temp\httpd-2.2.25-win32-x86-no_ssl.msi
      state: absent
