---
- hosts: all
  tasks:
    - name: Get Windows version
      win_shell: "systeminfo /fo csv | ConvertFrom-Csv | select \"OS Version\" | Format-List"
      register: windows_version
      when:
        - windows_version == "10.0.17763"

    - name: Print Windows host information
      debug:
        msg: "{{ windows_version }}"
