---
- hosts: all
  tasks:
    - name: Get Windows version
      win_shell: "[System.Environment]::OSVersion.Version.Major"
      register: windows_version

    - name: Print Windows host information
      debug:
        msg: "{{ windows_version }}"
