---
- name: Uninstall Tanium
  hosts: all

  tasks:
  - name: Download Tanium uninstall package
    win_get_url:
        url: https://ehc002123.ehc.honeywell.com/tools/windows/Tanium/uninstall/{{item}}
        dest: C:\Temp\{{item}}
        force: no
    with_items:
        - tanium.exe
        - show-client-in-add-remove-programs.vbs
        - set-service-permissions-back-to-default.vbs
        - reset_directory_permissions.vbs

# - name: Powershell commands to uninstall Tanium
#   win_shell: |
#     get-service 'LanmanServer' | Where {$_.Status -ne 'Running'} | start-service
